import pyautogui, time
plu_label_location_x, plu_label_location_y=pyautogui.locateCenterOnScreen("/home/princesethi/Pictures/Gui_Automation/plu_label.png")
pyautogui.click(plu_label_location_x+60,plu_label_location_y)
pyautogui.hotkey('ctrl', 'a')
pyautogui.hotkey('ctrl', 'v')
edit_btn_location=pyautogui.locateCenterOnScreen("/home/princesethi/Pictures/Gui_Automation/edit_btn.png")
pyautogui.click(edit_btn_location)
pyautogui.moveRel(-100,250, duration=1.5)
pyautogui.click()
time.sleep(1.0)
plu_label_location_x, plu_label_location_y=pyautogui.locateCenterOnScreen("/home/princesethi/Pictures/Gui_Automation/plu_label.png")
pyautogui.moveTo(plu_label_location_x-20,plu_label_location_y+45, duration=1.5)
pyautogui.click()
product_name_label_location_x, product_name_label_location_y=pyautogui.locateCenterOnScreen("/home/princesethi/Pictures/Gui_Automation/product_name_label.png")
pyautogui.moveTo(product_name_label_location_x+100, product_name_label_location_y)
pyautogui.click()
pyautogui.hotkey('ctrl', 'a')
pyautogui.hotkey('ctrl', 'v')
category_btn_location=pyautogui.locateCenterOnScreen("/home/princesethi/Pictures/Gui_Automation/category_btn.png")
pyautogui.click(category_btn_location)
category_movies_music_dropdown_location=pyautogui.locateCenterOnScreen("/home/princesethi/Pictures/Gui_Automation/category_movies_music_dropdown.png")
pyautogui.click(category_movies_music_dropdown_location)